### ISSUE TITLE
DHCP reload failed

### ISSUE THREAD

**Issue by 9ae8sdf76** [keexybox/keexyapp#7]
I am going through the config process, and after saving my DHCP networks, I get the message, "DHCP settings updated successfully. But DHCP reload failed." Looking at https://github.com/keexybox/keexyapp/blob/fb804ecf4a86541a81ed821ab5ded3c1a757ad86/src/Controller/ConfigController.php#L586 I checked my system, and I do not have `dhcp`. I do, however, have `dhcpcp`. 

- I am using the downloaded tarball (https://download.keexybox.org/keexybox_20.04.2_raspbian10.tar.gz)
- I'm running a Raspberry Pi 4 (4gb)
- I am currently on WiFi, but setting it up for Ethernet
- I am using the latest version of Raspbian (10.4)

**Comment by bsaglietto** [comment]
We prefer that only the bugs confirmed after investigation be reported on GitHub. It is preferable to use the KeexyBox forum before reporting an issue here. Someone had a similar issue as yours. See on our forum at https://forum.keexybox.org/thread-3.html. I hope this will help you to investigate.
