### ISSUE TITLE
Can't import StevenBlack blacklist

### ISSUE THREAD

**Issue by robward-basemap** [keexybox/keexyapp#9]
This is the list I've used for many users on my pi-hole.  When I try to import it, I get an error that states "Some lists were invalid to import domains to the Blacklist."

https://github.com/StevenBlack/hosts

**Comment by bsaglietto** [comment]
The import is done by this script `/opt/keexybox/keexyapp/src/Shell/scripts/blacklist-import-web.py`.
I tried to import manually running 
`python /opt/keexybox/keexyapp/src/Shell/scripts/blacklist-import-web.py -u https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts`

The script stop working at the first empty line.

```
Traceback (most recent call last):
  File "./blacklist-import-web-test.py", line 160, in <module>
    print line.split()[0]
IndexError: list index out of range
```
We will fix that. 
While waiting for the fix, the workaround is to create a new list containing just the domains by removing comments, empty lines and deleting 0.0.0.0.
